# Generated by Django 4.0.3 on 2022-11-12 03:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20221109_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='password2',
            field=models.CharField(editable=False, max_length=16, null=True, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(editable=False, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(editable=False, max_length=16, null=True, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(editable=False, max_length=50, null=True, unique=True),
        ),
    ]
