# Generated by Django 4.0.3 on 2022-11-12 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_usermodel_password2_alter_usermodel_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='password2',
        ),
    ]
