# Generated by Django 4.0.3 on 2022-11-12 03:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_usermodel_password2'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='password2',
            field=models.CharField(editable=False, max_length=16, null=True, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
